// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE30Ik2Gr83XQhd1osqMjD48GYSwkJ0nk',
    appId: '1:371890045758:web:8f6029924e3ed98862626f',
    messagingSenderId: '371890045758',
    projectId: 'messageboardapp-7a7e8',
    authDomain: 'messageboardapp-7a7e8.firebaseapp.com',
    storageBucket: 'messageboardapp-7a7e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeC88s7kuNQflrkzdy1wvt22J-eaJKel4',
    appId: '1:371890045758:android:2341d3b2981a672b62626f',
    messagingSenderId: '371890045758',
    projectId: 'messageboardapp-7a7e8',
    storageBucket: 'messageboardapp-7a7e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcfsRuKaL2o4Nbsj5PU0sPFSWH15mkMUQ',
    appId: '1:371890045758:ios:8119f196dab1b80562626f',
    messagingSenderId: '371890045758',
    projectId: 'messageboardapp-7a7e8',
    storageBucket: 'messageboardapp-7a7e8.firebasestorage.app',
    iosBundleId: 'com.example.homework2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcfsRuKaL2o4Nbsj5PU0sPFSWH15mkMUQ',
    appId: '1:371890045758:ios:8119f196dab1b80562626f',
    messagingSenderId: '371890045758',
    projectId: 'messageboardapp-7a7e8',
    storageBucket: 'messageboardapp-7a7e8.firebasestorage.app',
    iosBundleId: 'com.example.homework2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE30Ik2Gr83XQhd1osqMjD48GYSwkJ0nk',
    appId: '1:371890045758:web:6e240112616ce6b862626f',
    messagingSenderId: '371890045758',
    projectId: 'messageboardapp-7a7e8',
    authDomain: 'messageboardapp-7a7e8.firebaseapp.com',
    storageBucket: 'messageboardapp-7a7e8.firebasestorage.app',
  );
}
